apiVersion: v1
kind: Service
metadata:
  name: testapp
  namespace: default
spec:
  type: NodePort
  selector:
    app: testapp
  ports:
  - name: web
    protocol: TCP
    port: 8080
    nodePort: 30002
    targetPort: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: testapp
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testapp
    spec:
      containers:
      - name: testapp 
        image: bestcharles/testapp2
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
