apiVersion: v1
kind: Service
metadata:
  name: webservice
  namespace: default
spec:
  type: NodePort
  selector:
    app: webservice
  ports:
  - name: web
    protocol: TCP
    port: 8080
    nodePort: 30002
    targetPort: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webservice
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: webservice
    spec:
      containers:
      - name: webservice 
        image: bestcharles/webservice4
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
      nodeSelector:
        vdc: node1