kind: Service
apiVersion: v1
metadata:
  name: example-app
  labels:
    app: example-app
spec:
  type: NodePort
  ports:
  - name: web
    port: 8080
    nodePort: 30001
  selector:
    app: example-app
