apiVersion: v1
kind: Service
metadata:
  name: prometheus-app
  labels:
   app: example-app
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30999
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus-app