kind: Service
apiVersion: v1
metadata:
  name: example-app
  labels:
    tier: frontend
  namespace: default
spec:
  type: NodePort
  selector:
    app: example-app
  ports:
  - name: web
    protocol: TCP
    port: 8080
    nodePort: 30001
    targetPort: web
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-app
  namespace: default
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app 
        image: bestcharles/testapp4
        ports:
        - name: web
          containerPort: 8080
          protocol: TCP
      nodeSelector:
        vdc: node1
